### ISSUE TITLE
Build error: Cannot find module './transform.js'

### ISSUE THREAD

**Issue by brunetton** [jaebradley/tinder-client#68]
Hi, 

First of all, I'm sorry to ask, I'm a beginner in Node world, this problem is maybe super easy to fix !

I wanted to contribute to the lib, so I installed it as a linked module (from the last commit, ie `708d6a3d8ca54`), but the `build` script does not pass:

```
$ npm i      

> tinder-client@0.0.0-development prepare /home/bruno2/dev/js/tdr/tinder-client
> npm run build


> tinder-client@0.0.0-development build /home/bruno2/dev/js/tdr/tinder-client
> BABEL_ENV=production rollup -c


src/index.js → build/index.js, build/index.cjs.js, build/index.esm.js...
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
axios (guessing 'axios')
[!] (terser plugin) Error: Cannot find module './transform.js'
Error: Cannot find module './transform.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.renderChunk (/home/bruno2/dev/js/tdr/tinder-client/node_modules/rollup-plugin-terser/index.js:16:41)
    at /home/bruno2/dev/js/tdr/tinder-client/node_modules/rollup/dist/rollup.js:20831:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tinder-client@0.0.0-development build: `BABEL_ENV=production rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tinder-client@0.0.0-development build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bruno2/.npm/_logs/2019-01-29T12_17_35_248Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tinder-client@0.0.0-development prepare: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tinder-client@0.0.0-development prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bruno2/.npm/_logs/2019-01-29T12_17_35_280Z-debug.log
```

I tried to manually install axios as stated in the readme (`npm i axios`) but didn't changed anything.

Maybe I'm missing something ? I can't wait to send you my first PR ;)

Thanks !

```
$ npm --version
6.4.1
$ node --version
v10.15.0
```

**Comment by jaebradley** [comment]
@brunetton Thanks for opening this issue!

Sorry about the problems you've run into - after merging #69 you should be able to get started.

I haven't given this project the proper maintenance it deserves - after updating the out-of-date development dependencies, you should no longer be running into the issues that you're seeing.

You *will* need to get your facebook id and facebook token to run tests locally / in your fork of the repo. 

I'll add some notes to the `README` in-terms of how to generate these values soon, hopefully.

Please let me know if you run into any additional issues.

**Comment by brunetton** [comment]
Thank you SO MUCH :)

It works like a charm after linking the dependency (`npm link`). I just have to run `npm run prepare` to update code after each change. 

Thanks :) And see you sonn for some PRs :)
